---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dev.opt.sealos.io
  resources:
  - distributetrains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dev.opt.sealos.io
  resources:
  - distributetrains/finalizers
  verbs:
  - update
- apiGroups:
  - dev.opt.sealos.io
  resources:
  - distributetrains/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dev.opt.sealos.io
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dev.opt.sealos.io
  resources:
  - jobs/finalizers
  verbs:
  - update
- apiGroups:
  - dev.opt.sealos.io
  resources:
  - jobs/status
  verbs:
  - get
  - patch
  - update
